# Generated by Django 5.0.7 on 2024-07-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_reply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='dis', max_length=300),
            preserve_default=False,
        ),
    ]
