# Generated by Django 5.0.7 on 2024-07-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_discussion_options_discussion_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='name',
            new_name='title',
        ),
    ]
