# Generated by Django 5.0.7 on 2024-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_rating_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='volumes',
            field=models.IntegerField(default=0),
        ),
    ]
