# Generated by Django 5.0.7 on 2024-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_rating_chapters_alter_rating_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, '1 - Terrible'), (2, '2 - Very Bad'), (3, '3 - Bad'), (4, '4 - Below Average'), (5, '5 - Average'), (6, '6 - Above Average'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Excellent'), (10, '10 - Masterpiece')]),
        ),
    ]
