# Generated by Django 5.0.7 on 2024-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
