# Generated by Django 5.0.7 on 2024-07-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
