# Generated by Django 5.0.7 on 2024-07-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_friends_delete_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Stats',
        ),
    ]
