# Generated by Django 5.0.7 on 2024-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_alias_alter_author_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='authors/'),
        ),
    ]
