# Generated by Django 5.0.7 on 2024-07-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_author_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author_book',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
