# Generated by Django 5.0.7 on 2024-07-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('alternative_title', models.CharField(blank=True, max_length=300)),
                ('volumes', models.IntegerField(blank=True)),
                ('chapters', models.IntegerField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Completed'), (1, 'Publishing'), (-1, 'On Hiatus')])),
                ('synopsis', models.TextField()),
                ('background', models.TextField(blank=True)),
                ('publishing_start_date', models.DateField()),
                ('publishing_end_date', models.DateField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.genre'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ImageField(default='default.jpg', upload_to='books/')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_types', models.IntegerField(choices=[(0, 'Prequel'), (1, 'Sequel'), (2, 'Alternative Version'), (-1, 'Other')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('book_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relationship_from_set', to='books.book')),
                ('book_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relationship_to_set', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='relationships',
            field=models.ManyToManyField(through='books.Relationship', to='books.book'),
        ),
    ]
