# Generated by Django 5.0.7 on 2024-07-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='books/'),
        ),
    ]
