# Generated by Django 5.0.7 on 2024-07-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
