# Generated by Django 5.0.7 on 2024-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_publishing_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default_book.jpg', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='link',
            field=models.ImageField(default='default_book.jpg', upload_to='books/'),
        ),
    ]
