# Generated by Django 5.0.7 on 2024-07-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_alter_picture_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='link',
            new_name='picture',
        ),
    ]
