# Generated by Django 5.0.7 on 2024-07-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_link_picture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='alternative_title',
        ),
        migrations.AddField(
            model_name='book',
            name='alternative_titles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
    ]
