# Generated by Django 5.0.7 on 2024-07-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_alternative_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishing_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
