# Generated by Django 5.0.7 on 2024-07-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_publishing_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Related Entry', 'verbose_name_plural': 'Related Entries'},
        ),
        migrations.AlterField(
            model_name='relationship',
            name='book_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Relationship_to_set', to='books.book', verbose_name='Related Book'),
        ),
    ]
