# Generated by Django 5.0.7 on 2024-07-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_relationship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default_book.jpg', upload_to='books/covers/'),
        ),
    ]
