# Generated by Django 5.0.7 on 2024-07-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='relationship_types',
            new_name='relationship_type',
        ),
    ]
