# Generated by Django 5.0.7 on 2024-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_relationship_types_relationship_relationship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.IntegerField(choices=[(0, 'Prequel'), (1, 'Sequel'), (2, 'Alternative Version'), (3, 'Side Story'), (4, 'Parent Story'), (-1, 'Other')]),
        ),
    ]
