# Generated by Django 5.0.7 on 2024-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_stats_average_score_book_stats_popularity_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_stats',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
