# Generated by Django 5.0.7 on 2024-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default='default.png', upload_to='characters/'),
            preserve_default=False,
        ),
    ]
