# Generated by Django 5.0.7 on 2024-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_alias_alter_character_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='characters/'),
        ),
    ]
