# Generated by Django 5.0.7 on 2024-07-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_book_character_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character_book',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
    ]
